### ISSUE TITLE
Switch away from actix-web

### ISSUE THREAD

**Issue by MTRNord** [MTRNord/server_stats#27]

**Comment by MTRNord** [comment]
Will switch to https://docs.rs/warp/0.3.1/warp/filters/index.html most likely

**Comment by Glandos** [comment]
I'm just curious: given the fact that actix is much faster than warp, is there any technical reason to move away from it?

**Comment by MTRNord** [comment]
@Glandos In fact I experienced the opposite. Due to the fact that actix-web is singlethread and warp multithread warp will overall cause better performance with large amounts of async tasks like this uses.

Also apart from that actix is not Send so it adds a whole world of complexity to the code thats not happening using warp.
