### ISSUE TITLE
Bot generates a lot of events

### ISSUE THREAD

**Issue by tcitworld** [MTRNord/server_stats#28]
I'm in a Nextcloud related room (`!TEwfEWdDwdaFazXmwD:matrix.org`) and the bot seems to be generating always the same kind of events. As there are hundreds and hundreds of these, it makes it harder for the room to be loaded.

```json
{
  "content": {
    "avatar_url": "mxc://nordgedanken.dev/18fa3e54f2355f20a1fa45b16da7f0c6efc30e8f",
    "displayname": "Server Stats Discoverer (traveler bot)",
    "membership": "join"
  },
  "event_id": "$16226164132520UqbKN:nordgedanken.dev",
  "origin_server_ts": 1622616413181,
  "sender": "@server_stats:nordgedanken.dev",
  "state_key": "@server_stats:nordgedanken.dev",
  "type": "m.room.member",
  "age_ts": 1622616414024,
  "unsigned": {
    "age": 18,
    "replaces_state": "$16226163792518fTEsN:nordgedanken.dev",
    "prev_content": {
      "avatar_url": "mxc://nordgedanken.dev/18fa3e54f2355f20a1fa45b16da7f0c6efc30e8f",
      "displayname": "Server Stats Discoverer (traveler bot)",
      "membership": "join"
    },
    "prev_sender": "@server_stats:nordgedanken.dev"
  },
  "room_id": "!TEwfEWdDwdaFazXmwD:matrix.org"
}
```

**Comment by MTRNord** [comment]
Just to make sure: Does the room an alias so I can also block it in the code? As the bot doesnt resolve the room id before joining :)

**Comment by natrius** [comment]
#nextcloud_:matrix.org
#Nextcloud:matrix.org
#NEXTCLOUD:matrix.org
#NextCloud:matrix.org

I don't think there are other adresses. 

The room is roomversion #1, could that be a problem as well?

**Comment by MTRNord** [comment]
the room version doesnt matter I think. But thats probably more a thing synapse people know. I now stopped my bot from being allowed to join any of those aliases or the room id.

**Comment by tcitworld** [comment]
> I don't think there are other adresses.
> 
> The room is roomversion #1, could that be a problem as well?

@natrius These aliases are set as local addresses, but none of them are published as the principal one.
