### ISSUE TITLE
'Kick' does not work properly?

### ISSUE THREAD

**Issue by natrius** [MTRNord/server_stats#29]
According to the documentation, this is how to remove the bot: 

```
How To Remove The Bot From A Room

    You kick it -> This causes the bot to leave until the room is mentioned again somewhere.

```

I did kick the bot and did join on itself again without mentioning the server stat discoverer or traveler.

![grafik](https://user-images.githubusercontent.com/7243447/120439829-43c44380-c383-11eb-8289-a58c9aff3496.png)

For now i will ban the bot

**Comment by MTRNord** [comment]
For having it gone fully a ban is the correct way. this happened most likely because it found the room again and therefor joined back
